# Description: Configuration file for the API.
# Info: Restart the webserver for the changes to take effect.
#      The configuration file is in YAML format
server:
  debug: true # - Enable exception stack traces in console
  reload: true # - Reload the server when code changes
customization:
  title: 'API' # - Title of the API
routing:
  context_path: /api # - Base path for all API endpoints - must start with a forward slash - could break any harcoded URLs in the frontend
  enabled_versions: [1] # - List of enabled API versions - Enabling multiple will allow users to use any of the enabled versions, breaking changes could clash. - Must be a list
database:
  url: 'sqlite+aiosqlite:///./test.db' # - URL of the database - can be any SQLAlchemy compatible URL
  create_tables: false # - Create tables on startup/reload, this will delete all data on startup if set to true
session:
  cookie_identifier: 'session' # - Name of the cookie used to store the session ID - changing this invalidates all existing sessions
  user_max_sessions: 3 # - Maximum number of sessions a user can have at the same time - lowering this in production will cause issues for users
  session_max_age: 604800 # - Amount of time a session will last for (in seconds) - 604800 = 1 week
  session_cleanup_interval: 3600 # - Clear expired sessions every x seconds - 3600 = 1 hour
  cookie_secure: true # - Only send cookies over HTTPS - should always be true in production
  cookie_http_only: true # - Disallow JavaScript from accessing cookies - i.e. stopping them from being modified by malicious scripts/actors
2fa:
  enabled: true # - Allow users to choose to enable 2FA
  forced: false # - Force users to enable 2FA
  issuer_name: 'API' # - Name of the issuer for 2FA tokens
  digits: 6 # - Number of digits in a 2FA token
  period: 30 # - Time period for 2FA tokens (in seconds)

  backup_codes: 5 # - Number of recovery codes to generate
  backup_code_length: 16 # - Length of each recovery code (must be an even number)
email:
  host: 'smtp.gmail.com' # - SMTP server host
  port: 587 # - SMTP server port
  username: '' # - SMTP server username
  password: '' # - SMTP server password
  sender: '' # - Email address to send emails from

  # Further configuration for email OAuth:
  ## These variables are optional and when sending emails, the placeholder values will be replaced with the actual values
  ### {verification_url} - URL to verify the email address
  #### {login_url} - URL to login to the account
  ##### {reset_url} - URL to reset the password
  welcome_email:
    enabled: false # - Enable welcome emails
    subject: 'Welcome to the API' # - Subject of the welcome email
    plain_body: 'Welcome to the API!' # - Plain text body of the welcome email
    html_body_file: 'welcome_email.html' # - HTML body of the welcome email
  verification_email:
    enabled: false # - Enable email verification
    subject: 'Verify your email address' # - Subject of the verification email
    plain_body: 'Click the following link to verify your email address: {verification_url}' # - Plain text body of the verification email
    html_body_file: 'verification_email.html' # - HTML body of the verification email
  login_email:
    subject: 'Login to your API account!' # - Subject of the login email
    plain_body: 'Please click the following link to login to your account: {login_url}' # - Plain text body of the login email
    html_body_file: 'login_email.html' # - HTML body of the login email
  password_reset_email:
    enabled: false # - Enable password reset emails
    subject: 'Reset your password' # - Subject of the password reset email
    plain_body: 'Click the following link to reset your password: {reset_url}' # - Plain text body of the password reset email
    html_body_file: 'password_reset_email.html' # - HTML body of the password reset email
core:
  frontend_url: 'https://congenial-fiesta-9wj49x4455v2vwx-8000.app.github.dev' # - URL of the frontend - used for CORS and to redirect users
  encryption_key: 'wLtgFX0SyIB6V2gMTEmHIxEQNac5wpVuxlqIApGz7NM=' # - Key used to encrypt sensitive data in the database - must be 32 bytes long - can be generated with os.urandom(32) - DO NOT CHANGE THIS AFTER USERS HAVE REGISTERED
  password_salt: 'salt' # - Salt used to hash passwords - can be any string - DO NOT CHANGE THIS AFTER USERS HAVE REGISTERED
  cookie_secret: 'secret' # - Secret used to sign cookies - can be any string - Changing this will invalidate all existing sessions
  cookie_algorithm: 'HS256' # - Algorithm used to sign cookies - can be any algorithm supported by PyJWT - Changing this will invalidate all existing sessions
  default_avatar: 'https://cdn.discordapp.com/embed/avatars/0.png' # - Default avatar URL for new users - Should be a URL to an image
  password_min_length: 8 # - Minimum length of a users password - Changing this in production will not have any effect on existing users
  password_reset_code_expiry: 18000 # - Amount of time a password reset code will last for (in seconds)
oauth:
  email:
    enabled: false # - Enable email OAuth
    expiry: 1800 # - Amount of time an email OAuth code will last for (in seconds)
    # Further configuration for email OAuth in Email section
  discord:
    enabled: true # - Enable Discord OAuth
    client_id: '' # - Discord OAuth client ID
    client_secret: '' # - Discord OAuth client secret
    login_redirect_uri: 'https://congenial-fiesta-9wj49x4455v2vwx-8000.app.github.dev/api/v1/auth/oauth/callback/discord' # - Redirect URI for logging in with Discord OAuth
    link_redirect_uri: 'https://congenial-fiesta-9wj49x4455v2vwx-8000.app.github.dev/api/v1/account/link/callback/discord' # - Redirect URI for linking Discord OAuth to a user account
    scopes: ['identify', 'email'] # - Discord OAuth scopes
  google:
    enabled: false # - Enable Google OAuth
    client_id: '' # - Google OAuth client ID
    client_secret: '' # - Google OAuth client secret
    login_redirect_uri: 'https://congenial-fiesta-9wj49x4455v2vwx-8000.app.github.dev/api/v1/auth/oauth/callback/google' # - Redirect URI for logging in with Google OAuth
    link_redirect_uri: 'https://congenial-fiesta-9wj49x4455v2vwx-8000.app.github.dev/api/v1/account/link/callback/google' # - Redirect URI for linking Google OAuth to a user account
    scopes: ['profile', 'email'] # - Google OAuth scopes
  github:
    enabled: false # - Enable GitHub OAuth
    client_id: '' # - GitHub OAuth client ID
    client_secret: '' # - GitHub OAuth client secret
    login_redirect_uri: 'https://congenial-fiesta-9wj49x4455v2vwx-8000.app.github.dev/api/v1/auth/oauth/callback/github' # - Redirect URI for logging in with GitHub OAuth
    link_redirect_uri: 'https://congenial-fiesta-9wj49x4455v2vwx-8000.app.github.dev/api/v1/account/link/callback/github' # - Redirect URI for linking GitHub OAuth to a user account
    scopes: ['read:user', 'user:email'] # - GitHub OAuth scopes